export component Tooltip inherits Rectangle {
    in property <string> text;
    in property <bool> open: false;

    visible: open;
    background: #111827;
    border-radius: 6px;

    label := Text {
        x: 8px;
        y: 7px;
        width: parent.width - 16px;
        text: root.text;
        wrap: word-wrap;
        font-size: 12px;
        color: #ffffff;
    }

    height: label.preferred-height + 14px;
}
